include: package:webtrit_analysis/analysis_options.yaml

linter:
  rules:
    prefer_single_quotes: true

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "build/**"
    - "lib/generated/**"
  errors:
    library_private_types_in_public_api: ignore
    invalid_annotation_target: ignore

formatter:
  page_width: 120
