name: webtrit_configurator
description: A project that allows you to customize the style of the mobile application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <3.0.0"
  flutter: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  flutter_web_plugins:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  #DI
  injectable: ^2.1.0
  get_it: ^7.2.0

  # Localization
  intl: ^0.17.0

  # Navigation
  go_router: ^6.0.1
  url_launcher: ^6.1.5

  # State manager
  bloc: ^8.1.1
  flutter_bloc: ^8.1.2

  # Firebase
  firebase_core: ^2.7.1
  firebase_auth: ^4.2.10
  firebase_database: ^10.0.15
  firebase_storage: ^11.0.16

  # UI
  device_preview: ^1.1.0
  responsive_framework: ^0.2.0
  flutter_hsvcolor_picker: ^1.2.3
  image_picker: ^0.8.7+1
  image_picker_for_web: ^2.1.12
  flutter_svg: ^2.0.2

  # Generators
  freezed_annotation: ^2.2.0
  freezed: ^2.3.2
  json_annotation: ^4.8.0
  flutter_launcher_icons: ^0.12.0

  # Helpers
  meta: ^1.8.0
  formz: ^0.5.0
  validated: ^2.0.0
  logging: ^1.0.2
  logging_appenders: ^1.0.0
  collection: ^1.17.0

  # Plugins for support phone module
  connectivity_plus: ^3.0.2
  google_fonts: ^4.0.3
  path: ^1.8.2
  infinite_scroll_pagination: ^3.2.0

  # HTTP
  dio: ^5.1.0

  # The main dependency of the configuration object
  screenshots:
    path: ../webtrit_phone/screenshots
  webtrit_phone:
    path: ../webtrit_phone

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
  errors:
    invalid_annotation_target: ignore

dev_dependencies:
  flutter_test:
    sdk: flutter
  json_serializable: ^6.6.1
  injectable_generator: ^2.1.4
  bloc_test: ^9.1.1
  flutter_gen_runner: ^5.2.0
  flutter_lints: ^2.0.1
  build_runner: ^2.3.3

flutter:
  generate: true
  uses-material-design: true

dependency_overrides:
  google_fonts: ^4.0.3
