import 'package:flutter/material.dart';
import 'package:webtrit_configurator/share/exports/exports.dart';

class ColorSchemeModel extends ColorSchemeOverride {
  ColorSchemeModel({
    this.gradientTabColor = const [],
    super.primary,
    super.onPrimary,
    super.primaryContainer,
    super.onPrimaryContainer,
    super.secondary,
    super.onSecondary,
    super.secondaryContainer,
    super.onSecondaryContainer,
    super.tertiary,
    super.onTertiary,
    super.tertiaryContainer,
    super.error,
    super.onError,
    super.errorContainer,
    super.onErrorContainer,
    super.outline,
    super.outlineVariant,
    super.background,
    super.onBackground,
    super.surface,
    super.onSurface,
    super.surfaceVariant,
    super.onSurfaceVariant,
    super.inverseSurface,
    super.shadow,
    super.scrim,
    super.surfaceTint,
  });

  final List<Color> gradientTabColor;

  ColorSchemeModel copyWith({
    Color? primary,
    Color? onPrimary,
    Color? primaryContainer,
    Color? onPrimaryContainer,
    Color? secondary,
    Color? onSecondary,
    Color? secondaryContainer,
    Color? onSecondaryContainer,
    Color? tertiary,
    Color? onTertiary,
    Color? tertiaryContainer,
    Color? error,
    Color? onError,
    Color? errorContainer,
    Color? onErrorContainer,
    Color? outline,
    Color? outlineVariant,
    Color? background,
    Color? onBackground,
    Color? surface,
    Color? onSurface,
    Color? surfaceVariant,
    Color? onSurfaceVariant,
    Color? inverseSurface,
    Color? shadow,
    Color? scrim,
    Color? surfaceTint,
    List<Color>? gradientTabColor,
  }) {
    return ColorSchemeModel(
      primary: primary ?? this.primary,
      onPrimary: onPrimary ?? this.onPrimary,
      primaryContainer: primaryContainer ?? this.primaryContainer,
      onPrimaryContainer: onPrimaryContainer ?? this.onPrimaryContainer,
      secondary: secondary ?? this.secondary,
      onSecondary: onSecondary ?? this.onSecondary,
      secondaryContainer: secondaryContainer ?? this.secondaryContainer,
      onSecondaryContainer: onSecondaryContainer ?? this.onSecondaryContainer,
      tertiary: tertiary ?? this.tertiary,
      onTertiary: onTertiary ?? this.onTertiary,
      tertiaryContainer: tertiaryContainer ?? this.tertiaryContainer,
      error: error ?? this.error,
      onError: onError ?? this.onError,
      errorContainer: errorContainer ?? this.errorContainer,
      onErrorContainer: onErrorContainer ?? this.onErrorContainer,
      outline: outline ?? this.outline,
      outlineVariant: outlineVariant ?? this.outlineVariant,
      background: background ?? this.background,
      onBackground: onBackground ?? this.onBackground,
      surface: surface ?? this.surface,
      onSurface: onSurface ?? this.onSurface,
      surfaceVariant: surfaceVariant ?? this.surfaceVariant,
      onSurfaceVariant: onSurfaceVariant ?? this.onSurfaceVariant,
      inverseSurface: inverseSurface ?? this.inverseSurface,
      shadow: shadow ?? this.shadow,
      scrim: scrim ?? this.scrim,
      surfaceTint: surfaceTint ?? this.surfaceTint,
      gradientTabColor: gradientTabColor ?? this.gradientTabColor,
    );
  }

  List<Color> asList() => [
        if (primary != null) primary!,
        if (onPrimary != null) onPrimary!,
        if (secondary != null) secondary!,
        if (secondaryContainer != null) secondaryContainer!,
        if (onSecondaryContainer != null) onSecondaryContainer!,
        if (tertiary != null) tertiary!,
        if (error != null) error!,
        if (outline != null) outline!,
        if (background != null) background!,
        if (onBackground != null) onBackground!,
        if (surface != null) surface!,
        if (onSurface != null) onSurface!,
      ];
}
