import 'package:flutter/material.dart';

import 'package:webtrit_configurator/app/environment_config.dart';
import 'package:webtrit_configurator/core/widgets/widgets.dart';

import 'package:webtrit_configurator/localization/localization.dart';

import '../model/models.dart';

class ApplicationManage extends StatelessWidget {
  const ApplicationManage({
    super.key,
    required this.updateName,
    required this.updateIdentifier,
    required this.nameInput,
    required this.applicationIdentifierInput,
    required this.updateAndroidGoogleService,
    required this.updateIosGoogleService,
    required this.actionManage,
    required this.isAndroidGoogleServiceSelected,
    required this.isIosGoogleServiceSelected,
    required this.action,
  });

  final Function(String value) updateName;
  final Function(String value) updateIdentifier;

  final bool isAndroidGoogleServiceSelected;
  final bool isIosGoogleServiceSelected;

  final Function() updateAndroidGoogleService;
  final Function() updateIosGoogleService;

  final Function() actionManage;
  final String action;

  final ApplicationNameInput? nameInput;
  final ApplicationIdentifierInput? applicationIdentifierInput;

  @override
  Widget build(BuildContext context) {
    final colorScheme = Theme.of(context).colorScheme;
    final textScheme = Theme.of(context).textTheme;

    return ConstrainedBox(
      constraints: const BoxConstraints(maxWidth: 800, minWidth: 200),
      child: Card(
        elevation: 2,
        child: SingleChildScrollView(
          child: Container(
            margin: const EdgeInsets.symmetric(vertical: 64, horizontal: 16),
            child: Column(
              mainAxisSize: MainAxisSize.min,
              crossAxisAlignment: CrossAxisAlignment.start,
              mainAxisAlignment: MainAxisAlignment.center,
              children: [
                Text(
                  context.l10n.feature_application_Input_title,
                  style: textScheme.labelLarge,
                ),
                const SizedBox(
                  height: 4,
                ),
                TextFormField(
                  initialValue: nameInput?.value,
                  onChanged: updateName,
                  maxLength: ApplicationConsts.maxNameLimit,
                  decoration: InputDecoration(
                      errorText: nameInput?.errorL10n(context),
                      hintText: context.l10n.feature_application_Input_title,
                      hintStyle: textScheme.bodyMedium,
                      suffixIcon: Tooltip(
                        message: context.l10n.feature_application_create_Tooltip_name_info,
                        child: Icon(Icons.info_outlined, color: colorScheme.secondary),
                      )),
                ),
                Text(
                  context.l10n.feature_application_identifier,
                  style: Theme.of(context).textTheme.labelLarge,
                ),
                const SizedBox(
                  height: 4,
                ),
                TextFormField(
                  initialValue: applicationIdentifierInput?.value,
                  onChanged: updateIdentifier,
                  maxLength: ApplicationConsts.maxIdentifierLimit,
                  decoration: InputDecoration(
                    errorText: applicationIdentifierInput?.errorL10n(context),
                    suffixIcon: Tooltip(
                      message: context.l10n.feature_application_create_Tooltip_identifier_info,
                      child: Icon(Icons.info_outlined, color: colorScheme.secondary),
                    ),
                    prefixIcon: Column(
                      mainAxisAlignment: MainAxisAlignment.center,
                      children: [
                        Padding(
                          padding: const EdgeInsets.only(left: 8),
                          child: Text(
                            EnvironmentConfig.IDENTIFIER_PREFIX,
                            style: textScheme.bodyMedium?.copyWith(),
                          ),
                        )
                      ],
                    ),
                  ),
                ),
                const SizedBox(
                  height: 16,
                ),
                Row(
                  mainAxisAlignment: MainAxisAlignment.spaceBetween,
                  children: [
                    Text(
                      'Google services: ',
                      style: textScheme.labelLarge,
                    ),
                    Tooltip(
                      message:
                          'The google-services.json file is typically generated by the Google Play Console when you add a new app to your project.',
                      child: Container(
                        margin: const EdgeInsets.symmetric(horizontal: 8),
                        child: Icon(
                          Icons.info_outline,
                          color: Theme.of(context).colorScheme.tertiary,
                        ),
                      ),
                    ),
                  ],
                ),
                const SizedBox(
                  height: 8,
                ),
                Row(
                  children: [
                    GoogleServicesPreview(
                      platform: TargetPlatform.android,
                      type: isAndroidGoogleServiceSelected
                          ? GoogleServicesPreviewType.remove
                          : GoogleServicesPreviewType.add,
                      onTap: updateAndroidGoogleService,
                    ),
                    const SizedBox(width: 16),
                    GoogleServicesPreview(
                      type:
                          isIosGoogleServiceSelected ? GoogleServicesPreviewType.remove : GoogleServicesPreviewType.add,
                      platform: TargetPlatform.iOS,
                      onTap: updateIosGoogleService,
                    ),
                  ],
                ),
                const SizedBox(
                  height: 40,
                ),
                Button(
                  title: action,
                  onPressed: actionManage,
                ),
              ],
            ),
          ),
        ),
      ),
    );
  }
}
