// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    return const FirebaseOptions(
      apiKey: 'AIzaSyAUDdR2-iV_LGI42vFNLCtHM-Bd-EIoGsk',
      authDomain: 'webtrit-configurator.firebaseapp.com',
      databaseURL:
          'https://webtrit-configurator-default-rtdb.europe-west1.firebasedatabase.app',
      projectId: 'webtrit-configurator',
      storageBucket: 'webtrit-configurator.appspot.com',
      messagingSenderId: '242667391268',
      appId: '1:242667391268:web:3d40f4769e774b6ad64bb1',
      measurementId: 'G-HBK4609JQL',
    );
  }
}
