name: domain
description: A new Flutter project.
version: 0.0.1
publish_to: none

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  injectable: ^2.5.0
  get_it: ^8.0.3
  freezed_annotation: ^2.4.4
  freezed: ^2.5.7
  json_annotation: ^4.9.0

dev_dependencies:
  webtrit_analysis:
    git: https://github.com/WebTrit/webtrit_analysis.git

  material_color_utilities: 0.11.1
  flutter_gen_runner: ^5.8.0
  json_serializable: ^6.9.0
  injectable_generator: ^2.6.2
  build_runner: ^2.4.14
