name: domain
description: A new Flutter project.
version: 0.0.1
publish_to: none

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  injectable: ^2.4.1
  get_it: ^7.7.0
  freezed_annotation: ^2.4.1
  freezed: ^2.5.2
  data:
    path: ../data
  dto:
    git:
      url: https://github.com/WebTrit/webtrit_phone_configurator_common.git
      ref: main
      path: packages/dto

dependency_overrides:
  material_color_utilities: 0.12.0

  webtrit_analysis:
    git: https://github.com/WebTrit/webtrit_analysis.git
  flutter_gen_runner: ^5.4.0
  json_serializable: ^6.7.1
  injectable_generator: ^2.6.1
  build_runner_core: ^7.3.0
  build_runner: ^2.4.9
