name: domain
description: A new Flutter project.
version: 0.0.1
publish_to: none

environment:
  sdk: '>=3.1.3 <4.0.0'
  flutter: ^3.13.6

dependencies:
  #DI
  injectable: ^2.3.0
  get_it: ^7.6.4

  # Generators
  freezed_annotation: ^2.4.1
  freezed: ^2.4.3

  data:
    path: ../data

  dto:
    path: ../dto

dependency_overrides:
  # Generators
  freezed: 2.4.3

  # Linter
  analyzer: ^6.2.0

  # Tools
  collection: ^1.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Linter
  flutter_lints: ^2.0.2

  # Generators
  flutter_gen_runner: ^5.3.1
  json_serializable: ^6.7.1
  injectable_generator: ^2.4.0
  build_runner_core: ^7.2.9
  build_runner: ^2.4.6

flutter:
  generate: true
