export const TYPES = {
	Applications: Symbol.for('Application'),
	FirestoreDatasource: Symbol.for('FirestoreDatasource'),
	StaticRepository: Symbol.for('StaticRepository'),
	ApplicationRepository: Symbol.for('ApplicationRepository'),
	ThemeRepository: Symbol.for('ThemeRepository'),
	ApplicationsService: Symbol.for('ApplicationsService'),
	AuthService: Symbol.for('AuthService'),
	StaticService: Symbol.for('StaticService'),
	StaticController: Symbol.for('StaticController'),
	ThemeService: Symbol.for('ThemeService'),
	ApplicationController: Symbol.for('ApplicationController'),
	ThemeController: Symbol.for('ThemeController'),
	AuthTrigger: Symbol.for('AuthTrigger'),
	ApplicationTrigger: Symbol.for('ApplicationTrigger'),
	ExceptionFilter: Symbol.for('ExceptionFilter'),
	// Mapper
	FirestoreApplicationMapper: Symbol.for('FirestoreApplicationMapper'),
	FirestoreThemeMapper: Symbol.for('FirestoreThemeMapper'),
}
